# -*- coding: utf-8 -*-
"""
SözEğitim - Oxford 3000 / CEFR En Popüler 500+ Kelime Havuzu Aktarma Scripti
A1, A2, B1, B2, C1, C2 seviyelerinde en çok kullanılan kelimeleri veritabanına ekler.
"""

import os
import sqlite3
import json

db_path = os.path.join(os.path.dirname(__file__), "sozegitim.db")
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# 500+ En Popüler ve Kaliteli Kelime Listesi
POPULAR_WORDS = [
    # ==================== A1 (BAŞLANGIÇ - En Temel Günlük Kelimeler) ====================
    ("About", "Hakkında, yaklaşık", "A1", "/əˈbaʊt/", "edat", "We talked about our future plans.", "We are talking about you."),
    ("After", "Sonra, ardından", "A1", "/ˈɑːf.tər/", "edat", "Let's meet after school.", "I will call you after work."),
    ("Again", "Tekrar, yine", "A1", "/əˈɡen/", "zarf", "Can you please say that again?", "Try again tomorrow."),
    ("Always", "Her zaman, daima", "A1", "/ˈɔːl.weɪz/", "zarf", "She always arrives on time.", "He always smiles."),
    ("Animal", "Hayvan", "A1", "/ˈæn.ɪ.məl/", "isim", "Dolphins are very intelligent animals.", "I love wild animals."),
    ("Answer", "Cevap, yanıt vermek", "A1", "/ˈɑːn.sər/", "fiil", "Please answer my question.", "She gave a quick answer."),
    ("Ask", "Sormak, istemek", "A1", "/ɑːsk/", "fiil", "Don't be afraid to ask for help.", "Can I ask a question?"),
    ("Baby", "Bebek", "A1", "/ˈbeɪ.bi/", "isim", "The baby is sleeping peacefully.", "A cute baby."),
    ("Back", "Geri, arka, sırt", "A1", "/bæk/", "isim", "I will be back in ten minutes.", "Stand back please."),
    ("Bad", "Kötü, fena", "A1", "/bæd/", "sıfat", "Smoking is very bad for health.", "That was a bad idea."),
    ("Ball", "Top", "A1", "/bɔːl/", "isim", "The kids are playing with a ball.", "Kick the ball."),
    ("Bank", "Banka, kıyı", "A1", "/bæŋk/", "isim", "I need to go to the bank today.", "Along the river bank."),
    ("Beautiful", "Güzel, harika", "A1", "/ˈbjuː.tɪ.fəl/", "sıfat", "Istanbul is a beautiful city.", "A beautiful morning."),
    ("Bed", "Yatak", "A1", "/bed/", "isim", "It is time to go to bed.", "A comfortable bed."),
    ("Begin", "Başlamak", "A1", "/bɪˈɡɪn/", "fiil", "Classes begin at eight o'clock.", "Let the game begin."),
    ("Big", "Büyük, iri", "A1", "/bɪɡ/", "sıfat", "They live in a big house.", "A big success."),
    ("Bird", "Kuş", "A1", "/bɜːd/", "isim", "Early birds catch the worm.", "Look at the colorful bird."),
    ("Black", "Siyah, kara", "A1", "/blæk/", "sıfat", "He wore a black jacket.", "A black coffee."),
    ("Blue", "Mavi", "A1", "/bluː/", "sıfat", "The ocean looks deep blue.", "Under the blue sky."),
    ("Body", "Vücut, beden", "A1", "/ˈbɒd.i/", "isim", "Regular exercise keeps your body fit.", "A healthy body."),
    ("Boy", "Erkek çocuk", "A1", "/bɔɪ/", "isim", "The boy is riding his bicycle.", "A clever boy."),
    ("Bread", "Ekmek", "A1", "/bred/", "isim", "Fresh bread smells wonderful.", "Eat bread and cheese."),
    ("Brother", "Erkek kardeş", "A1", "/ˈbrʌð.ər/", "isim", "My brother studies engineering.", "He is my older brother."),
    ("Busy", "Meşgul, yoğun", "A1", "/ˈbɪz.i/", "sıfat", "I am very busy with my project.", "A busy street."),
    ("Buy", "Satın almak", "A1", "/baɪ/", "fiil", "I want to buy a new laptop.", "Where did you buy it?"),
    ("Call", "Aramak, seslenmek", "A1", "/kɔːl/", "fiil", "Call me when you arrive home.", "Give me a call."),
    ("Car", "Araba, otomobil", "A1", "/kɑːr/", "isim", "He parked his car outside.", "A red electric car."),
    ("City", "Şehir, kent", "A1", "/ˈsɪt.i/", "isim", "London is an ancient city.", "A crowded modern city."),
    ("Clean", "Temiz, temizlemek", "A1", "/kliːn/", "sıfat", "Keep your room clean and tidy.", "Drink clean water."),
    ("Clock", "Saat (duvar/masa)", "A1", "/klɒk/", "isim", "The clock on the wall stopped.", "Look at the clock."),
    ("Cold", "Soğuk", "A1", "/kəʊld/", "sıfat", "Winter nights are very cold.", "I caught a cold."),
    ("Color", "Renk", "A1", "/ˈkʌl.ər/", "isim", "What is your favorite color?", "Bright colors of nature."),
    ("Cook", "Yemek pişirmek, aşçı", "A1", "/kʊk/", "fiil", "She loves to cook Italian food.", "He is an amazing cook."),
    ("Country", "Ülke, memleket", "A1", "/ˈkʌn.tri/", "isim", "Turkey is a wonderful country.", "Travel to another country."),
    ("Day", "Gün, gündüz", "A1", "/deɪ/", "isim", "Have a productive day!", "One sunny day."),
    ("Door", "Kapı", "A1", "/dɔːr/", "isim", "Please close the door gently.", "Knock on the door."),
    ("Drink", "İçmek, içecek", "A1", "/drɪŋk/", "fiil", "Drink water every morning.", "Hot drinks in winter."),
    ("Drive", "Araba sürmek", "A1", "/draɪv/", "fiil", "Drive carefully in rainy weather.", "Learn to drive."),
    ("Easy", "Kolay, zahmetsiz", "A1", "/ˈiː.zi/", "sıfat", "English grammar is easy to learn.", "Take it easy."),
    ("Eat", "Yemek yemek", "A1", "/iːt/", "fiil", "Eat healthy fruits every day.", "What do you want to eat?"),
    ("Eye", "Göz", "A1", "/aɪ/", "isim", "She looked directly into my eyes.", "Blue eyes."),
    ("Fast", "Hızlı, çabuk", "A1", "/fɑːst/", "sıfat", "Cheetahs run remarkably fast.", "A fast internet connection."),
    ("Father", "Baba", "A1", "/ˈfɑː.ðər/", "isim", "My father is a kind teacher.", "Proud father."),
    ("Fish", "Balık", "A1", "/fɪʃ/", "isim", "Fish swim in the clear lake.", "Fresh grilled fish."),
    ("Food", "Yiyecek, gıda", "A1", "/fuːd/", "isim", "Good food gives you energy.", "Delicious Turkish food."),
    ("Game", "Oyun, maç", "A1", "/ɡeɪm/", "isim", "Let's play a word game.", "An exciting football game."),
    ("Girl", "Kız çocuk", "A1", "/ɡɜːl/", "isim", "The girl smiled warmly.", "A smart young girl."),
    ("Good", "İyi, güzel", "A1", "/ɡʊd/", "sıfat", "That is a very good question.", "Good job!"),
    ("Green", "Yeşil", "A1", "/ɡriːn/", "sıfat", "The grass is green in spring.", "Drink green tea."),
    ("Hand", "El", "A1", "/hænd/", "isim", "Wash your hands before eating.", "Give me a hand."),
    ("Hear", "Duymak, işitmek", "A1", "/hɪər/", "fiil", "Can you hear the birds singing?", "I heard the news."),
    ("Help", "Yardım etmek, yardım", "A1", "/help/", "fiil", "I am happy to help you.", "Thank you for your help."),
    ("Home", "Ev, yuva", "A1", "/həʊm/", "isim", "Welcome to our sweet home.", "Stay safe at home."),
    ("Hour", "Saat (süre)", "A1", "/aʊər/", "isim", "The flight takes two hours.", "Wait for an hour."),
    ("Learn", "Öğrenmek", "A1", "/lɜːn/", "fiil", "You learn new words every day.", "Learn by practicing."),
    ("Life", "Hayat, yaşam", "A1", "/laɪf/", "isim", "Life is full of wonderful moments.", "A peaceful life."),
    ("Listen", "Dinlemek", "A1", "/ˈlɪs.ən/", "fiil", "Listen carefully to the teacher.", "Listen to good music."),
    ("Love", "Sevmek, aşk", "A1", "/lʌv/", "fiil", "I love reading interesting books.", "Spread love and peace."),
    ("Morning", "Sabah", "A1", "/ˈmɔː.nɪŋ/", "isim", "Good morning to all students!", "Early in the morning."),
    ("Name", "İsim, ad", "A1", "/neɪm/", "isim", "What is your full name?", "Write your name here."),
    ("Night", "Gece", "A1", "/naɪt/", "isim", "Good night and sweet dreams.", "Stars shine at night."),
    ("Open", "Açık, açmak", "A1", "/ˈəʊ.pən/", "fiil", "Open the window for fresh air.", "Keep an open mind."),
    ("People", "İnsanlar, halk", "A1", "/ˈpiː.pəl/", "isim", "Kind people make the world better.", "Many people gathered."),
    ("Read", "Okumak", "A1", "/riːd/", "fiil", "Read daily to expand vocabulary.", "Read the next chapter."),
    ("Right", "Doğru, hak, sağ", "A1", "/raɪt/", "sıfat", "You made the right choice.", "Turn right at the corner."),
    ("Room", "Oda, yer", "A1", "/ruːm/", "isim", "My study room is quiet.", "There is enough room."),
    ("Sleep", "Uyumak, uyku", "A1", "/sliːp/", "fiil", "Get eight hours of sleep.", "Deep and restful sleep."),
    ("Small", "Küçük, ufak", "A1", "/smɔːl/", "sıfat", "Small steps lead to big goals.", "A small friendly cat."),
    ("Smile", "Gülümsemek, tebessüm", "A1", "/smaɪl/", "fiil", "Her warm smile made my day.", "Always smile."),
    ("Speak", "Konuşmak", "A1", "/spiːk/", "fiil", "Practice to speak English fluently.", "Speak with confidence."),
    ("Student", "Öğrenci", "A1", "/ˈstjuː.dənt/", "isim", "She is a hardworking student.", "University students."),
    ("Time", "Zaman, vakit", "A1", "/taɪm/", "isim", "Time is our most valuable asset.", "Take your time."),
    ("Today", "Bugün", "A1", "/təˈdeɪ/", "zarf", "Start your journey today.", "Today is a great day."),
    ("Walk", "Yürümek, yürüyüş", "A1", "/wɔːk/", "fiil", "Walk twenty minutes every day.", "Go for an evening walk."),
    ("Work", "Çalışmak, iş", "A1", "/wɜːk/", "fiil", "Hard work brings true success.", "I work with passion."),
    ("Write", "Yazmak", "A1", "/raɪt/", "fiil", "Write your thoughts in a journal.", "Write clean code."),

    # ==================== A2 (TEMEL - Günlük İletişim & Genişleyen Kelime Dağarcığı) ====================
    ("Abroad", "Yurt dışı, gurbet", "A2", "/əˈbrɔːd/", "zarf", "She wants to study abroad next year.", "Travel abroad."),
    ("Accident", "Kaza, rastlantı", "A2", "/ˈæk.sɪ.dənt/", "isim", "Drive carefully to prevent accidents.", "Traffic accident."),
    ("Achieve", "Başarmak, elde etmek", "A2", "/əˈtʃiːv/", "fiil", "You will achieve all your goals.", "Achieve high scores."),
    ("Activity", "Etkinlik, faaliyet", "A2", "/ækˈtɪv.ə.ti/", "isim", "Physical activity improves mental focus.", "Outdoor activities."),
    ("Afford", "Maddi gücü yetmek", "A2", "/əˈfɔːd/", "fiil", "We can afford this new car.", "Afford education."),
    ("Agree", "Aynı fikirde olmak, anlaşmak", "A2", "/əˈɡriː/", "fiil", "I completely agree with your opinion.", "Agree on a solution."),
    ("Airport", "Havalimanı", "A2", "/ˈeə.pɔːt/", "isim", "We arrived at the airport early.", "International airport."),
    ("Allow", "İzin vermek", "A2", "/əˈlaʊ/", "fiil", "Smoking is not allowed here.", "Allow me to introduce myself."),
    ("Almost", "Neredeyse, hemen hemen", "A2", "/ˈɔːl.məʊst/", "zarf", "We have almost finished the lesson.", "Almost ready."),
    ("Already", "Çoktan, zaten", "A2", "/ɔːlˈred.i/", "zarf", "I have already completed the quiz.", "She already knows."),
    ("Although", "Rağmen, -e karşın", "A2", "/ɔːlˈðəʊ/", "bağlaç", "Although it rained, we enjoyed the trip.", "Although tired, he worked."),
    ("Amount", "Miktar, tutar", "A2", "/əˈmaʊnt/", "isim", "Drink a sufficient amount of water.", "A large amount."),
    ("Angry", "Kızgın, öfkeli", "A2", "/ˈæŋ.ɡri/", "sıfat", "Take deep breaths when you feel angry.", "Do not get angry."),
    ("Anxious", "Endişeli, kaygılı", "A2", "/ˈæŋk.ʃəs/", "sıfat", "Students feel anxious before exams.", "Anxious about future."),
    ("Area", "Alan, bölge", "A2", "/ˈeə.ri.ə/", "isim", "The play area is safe for children.", "Rural and urban areas."),
    ("Arrive", "Varmak, ulaşmak", "A2", "/əˈraɪv/", "fiil", "The train will arrive at five.", "Arrive safely."),
    ("Article", "Makale, yazı, nesne", "A2", "/ˈɑː.tɪ.kəl/", "isim", "He published a fascinating article.", "Read scientific articles."),
    ("Artist", "Sanatçı, ressam", "A2", "/ˈɑː.tɪst/", "isim", "The artist painted a masterpiece.", "Talented young artist."),
    ("Attend", "Katılmak, devam etmek", "A2", "/əˈtend/", "fiil", "All students should attend classes.", "Attend a conference."),
    ("Attitude", "Tutum, tavır", "A2", "/ˈæt.ɪ.tʃuːd/", "isim", "A positive attitude changes everything.", "Friendly attitude."),
    ("Average", "Ortalama", "A2", "/ˈæv.ər.ɪdʒ/", "sıfat", "The average temperature is rising.", "Above average score."),
    ("Avoid", "Kaçınmak, uzak durmak", "A2", "/əˈvɔɪd/", "fiil", "Avoid negative self-talk.", "Avoid distractions."),
    ("Belong", "Ait olmak", "A2", "/bɪˈlɒŋ/", "fiil", "This book belongs to the library.", "Belong to a community."),
    ("Borrow", "Ödünç almak", "A2", "/ˈbɒr.əʊ/", "fiil", "Can I borrow your pencil for a minute?", "Borrow money."),
    ("Bother", "Rahatsız etmek, can sıkmak", "A2", "/ˈbɒð.ər/", "fiil", "Sorry to bother you right now.", "Do not bother about small things."),
    ("Brain", "Beyin, zeka", "A2", "/breɪn/", "isim", "Learning languages sharpens your brain.", "Human brain."),
    ("Breathe", "Nefes almak", "A2", "/briːð/", "fiil", "Breathe deeply and relax your muscles.", "Breathe fresh air."),
    ("Bridge", "Köprü", "A2", "/brɪdʒ/", "isim", "The historical bridge crosses the river.", "Build bridges not walls."),
    ("Careful", "Dikkatli, özenli", "A2", "/ˈkeə.fəl/", "sıfat", "Be careful when crossing the street.", "A careful driver."),
    ("Century", "Yüzyıl, asır", "A2", "/ˈsen.tʃər.i/", "isim", "We live in the twenty-first century.", "Last century."),
    ("Chance", "Şans, olasılık, fırsat", "A2", "/tʃɑːns/", "isim", "Give yourself a second chance.", "A good chance to learn."),
    ("Change", "Değişmek, değişiklik", "A2", "/tʃeɪndʒ/", "fiil", "Small habits change your life.", "Change the world."),
    ("Choose", "Seçmek, tercih etmek", "A2", "/tʃuːz/", "fiil", "Choose your goals with care.", "Choose wisely."),
    ("Clear", "Açık, net, berrak", "A2", "/klɪər/", "sıfat", "The instructions were very clear.", "Clear blue sky."),
    ("Collect", "Toplamak, biriktirmek", "A2", "/kəˈlekt/", "fiil", "He loves to collect vintage stamps.", "Collect useful data."),
    ("Comfortable", "Rahat, konforlu", "A2", "/ˈkʌm.fə.tə.bəl/", "sıfat", "These shoes are very comfortable.", "A comfortable chair."),
    ("Common", "Yaygın, ortak", "A2", "/ˈkɒm.ən/", "sıfat", "Flu is very common in autumn.", "Common goals."),
    ("Company", "Şirket, ortaklık", "A2", "/ˈkʌm.pə.ni/", "isim", "She founded a tech company.", "Keep good company."),
    ("Compare", "Kıyaslamak, karşılaştırmak", "A2", "/kəmˈpeər/", "fiil", "Do not compare yourself to others.", "Compare results."),
    ("Condition", "Durum, şart, koşul", "A2", "/kənˈdɪʃ.ən/", "isim", "The car is in excellent condition.", "Weather conditions."),
    ("Connect", "Bağlamak, bağlanmak", "A2", "/kəˈnekt/", "fiil", "Technology connects people globally.", "Connect to internet."),
    ("Continue", "Devam etmek", "A2", "/kənˈtɪn.juː/", "fiil", "Continue practicing every day.", "The story continues."),
    ("Control", "Kontrol etmek, denetim", "A2", "/kənˈtrəʊl/", "fiil", "Learn to control your emotions.", "Under full control."),
    ("Culture", "Kültür, medeniyet", "A2", "/ˈkʌl.tʃər/", "isim", "Travel introduces you to new cultures.", "Rich cultural heritage."),
    ("Customer", "Müşteri", "A2", "/ˈkʌs.tə.mər/", "isim", "Customer satisfaction is paramount.", "Regular customer."),
    ("Decide", "Karar vermek", "A2", "/dɪˈsaɪd/", "fiil", "Decide what matters most to you.", "Decide quickly."),
    ("Describe", "Tanımlamak, tarif etmek", "A2", "/dɪˈskraɪb/", "fiil", "Can you describe the picture?", "Describe feelings."),
    ("Develop", "Geliştirmek, gelişmek", "A2", "/dɪˈvel.əp/", "fiil", "Reading helps you develop vocabulary.", "Develop software."),
    ("Different", "Farklı, değişik", "A2", "/ˈdɪf.ər.ənt/", "sıfat", "Everyone has different talents.", "A different view."),
    ("Difficult", "Zor, güç", "A2", "/ˈdɪf.ɪ.kəlt/", "sıfat", "Nothing is difficult with practice.", "A difficult puzzle."),
    ("Direct", "Doğrudan, direkt", "A2", "/daɪˈrekt/", "sıfat", "Take the direct flight to Paris.", "Direct contact."),
    ("Discover", "Keşfetmek", "A2", "/dɪˈskʌv.ər/", "fiil", "Discover new words every single day.", "Discover science."),
    ("Distance", "Mesafe, uzaklık", "A2", "/ˈdɪs.təns/", "isim", "Long distance relationships require trust.", "A short distance."),
    ("Dream", "Rüya, hayal etmek", "A2", "/driːm/", "isim", "Follow your dream with courage.", "Dream big."),
    ("Early", "Erken, vaktinden önce", "A2", "/ˈɜː.li/", "zarf", "Waking up early gives you extra hours.", "Early morning."),
    ("Education", "Eğitim, öğretim", "A2", "/ˌedʒ.ʊˈkeɪ.ʃən/", "isim", "Education opens the door of wisdom.", "Quality education."),
    ("Effort", "Çaba, gayret", "A2", "/ˈef.ət/", "isim", "Success demands consistent daily effort.", "Put effort into studying."),
    ("Energy", "Enerji, güç", "A2", "/ˈen.ə.dʒi/", "isim", "Positive thoughts give positive energy.", "Clean solar energy."),
    ("Environment", "Çevre, ortam", "A2", "/ɪnˈvaɪ.rən.mənt/", "isim", "Protect our natural environment.", "Work environment."),
    ("Event", "Olay, etkinlik", "A2", "/ɪˈvent/", "isim", "The tech event was a great success.", "Historical events."),
    ("Everywhere", "Her yerde", "A2", "/ˈev.ri.weər/", "zarf", "Kindness should be everywhere.", "Search everywhere."),
    ("Example", "Örnek, misal", "A2", "/ɪɡˈzɑːm.pəl/", "isim", "Lead by good example.", "For example."),
    ("Expect", "Ummak, beklemek", "A2", "/ɪkˈspekt/", "fiil", "Do not expect instant perfection.", "Expect success."),
    ("Experience", "Deneyim, tecrübe", "A2", "/ɪkˈspɪə.ri.əns/", "isim", "Experience is the best teacher.", "Valuable life experience."),
    ("Explain", "Açıklamak, izah etmek", "A2", "/ɪkˈspleɪn/", "fiil", "Let me explain the grammar rule.", "Explain simply."),
    ("Express", "İfade etmek, hızlı", "A2", "/ɪkˈspres/", "fiil", "Express your thoughts clearly.", "Express train."),
    ("Famous", "Ünlü, meşhur", "A2", "/ˈfeɪ.məs/", "sıfat", "He became famous around the world.", "A famous author."),
    ("Feel", "Hissetmek, sezmek", "A2", "/fiːl/", "fiil", "I feel energized and focused.", "Feel confident."),
    ("Future", "Gelecek, istikbal", "A2", "/ˈfjuː.tʃər/", "isim", "Your future is shaped by today.", "Bright future."),
    ("General", "Genel, umumi", "A2", "/ˈdʒen.ər.əl/", "sıfat", "In general, exercise improves sleep.", "General knowledge."),

    # ==================== B1 (ORTA - Akıcı İletişim, Tartışma ve Fikir Belirtme) ====================
    ("Absence", "Yokluk, bulunmama", "B1", "/ˈæb.səns/", "isim", "His absence was noticed by all.", "In the absence of doubt."),
    ("Absolute", "Kesin, mutlak", "B1", "/ˈæb.sə.luːt/", "sıfat", "I have absolute confidence in you.", "Absolute truth."),
    ("Accurate", "Doğru, kesin, hatasız", "B1", "/ˈæk.jə.rət/", "sıfat", "Provide accurate data for the report.", "Accurate translation."),
    ("Adapt", "Uyum sağlamak, adapte olmak", "B1", "/əˈdæpt/", "fiil", "Humans adapt quickly to new surroundings.", "Adapt to changes."),
    ("Adequate", "Yeterli, kafi", "B1", "/ˈæd.ə.kwət/", "sıfat", "Ensure you get adequate rest.", "Adequate resources."),
    ("Admire", "Hayran olmak, takdir etmek", "B1", "/ədˈmaɪər/", "fiil", "I admire her relentless dedication.", "Admire the view."),
    ("Admit", "İtiraf etmek, kabul etmek", "B1", "/ədˈmɪt/", "fiil", "He admitted his mistake gracefully.", "Admit the truth."),
    ("Advance", "İlerlemek, terfi, avans", "B1", "/ədˈvɑːns/", "fiil", "Technology advances at high speed.", "In advance."),
    ("Advantage", "Avantaj, üstünlük", "B1", "/ədˈvɑːn.tɪdʒ/", "isim", "Bilingualism offers a huge advantage.", "Take advantage of."),
    ("Affect", "Etkilemek, tesir etmek", "B1", "/əˈfekt/", "fiil", "Sleep habits directly affect memory.", "Affect positively."),
    ("Alternative", "Alternatif, seçenek", "B1", "/ɒlˈtɜː.nə.tɪv/", "isim", "Renewable energy is our best alternative.", "Alternative routes."),
    ("Analyze", "İncelemek, analiz etmek", "B1", "/ˈæn.əl.aɪz/", "fiil", "Scientists analyze complex datasets.", "Analyze market trends."),
    ("Announce", "Duyurmak, ilan etmek", "B1", "/əˈnaʊns/", "fiil", "They will announce the quiz winners.", "Announce results."),
    ("Appreciate", "Takdir etmek, değerini bilmek", "B1", "/əˈpriː.ʃi.eɪt/", "fiil", "I deeply appreciate your continuous support.", "Appreciate art."),
    ("Approach", "Yaklaşım, yaklaşmak", "B1", "/əˈprəʊtʃ/", "isim", "Adopt a modern approach to learning.", "New scientific approach."),
    ("Appropriate", "Uygun, yerinde", "B1", "/əˈprəʊ.pri.ət/", "sıfat", "Choose clothing appropriate for the weather.", "Appropriate response."),
    ("Argue", "Tartışmak, iddia etmek", "B1", "/ˈɑːɡ.juː/", "fiil", "Scholars argue different theories.", "Argue logically."),
    ("Attempt", "Girişim, denemek", "B1", "/əˈtempt/", "isim", "Her first attempt was successful.", "Attempt to solve."),
    ("Attract", "Çekmek, cezbetmek", "B1", "/əˈtrækt/", "fiil", "The festival attracts tourists globally.", "Attract attention."),
    ("Aware", "Farkında, haberdar", "B1", "/əˈweər/", "sıfat", "Be aware of your strengths and weaknesses.", "Fully aware."),
    ("Beneficial", "Yararlı, faydalı", "B1", "/ˌben.ɪˈfɪʃ.əl/", "sıfat", "Meditation is beneficial for mental calm.", "Beneficial habits."),
    ("Capable", "Yetenekli, muktedir", "B1", "/ˈkeɪ.pə.bəl/", "sıfat", "You are capable of mastering languages.", "Highly capable."),
    ("Certain", "Belirli, kesin, emin", "B1", "/ˈsɜː.tən/", "sıfat", "I am certain you will pass the exam.", "Under certain terms."),
    ("Circumstance", "Durum, koşul, hal", "B1", "/ˈsɜː.kəm.stɑːns/", "isim", "Under no circumstance give up hope.", "Unforeseen circumstances."),
    ("Combine", "Birleştirmek, kaynaştırmak", "B1", "/kəmˈbaɪn/", "fiil", "Combine theory with hands-on practice.", "Combine elements."),
    ("Commitment", "Bağlılık, taahhüt", "B1", "/kəˈmɪt.mənt/", "isim", "Mastery requires deep daily commitment.", "Long term commitment."),
    ("Communicate", "İletişim kurmak", "B1", "/kəˈmjuː.nɪ.keɪt/", "fiil", "Communicate with respect and empathy.", "Communicate openly."),
    ("Compete", "Yarışmak, rekabet etmek", "B1", "/kəmˈpiːt/", "fiil", "Athletes compete for gold medals.", "Compete fairly."),
    ("Complicated", "Karmaşık, çetrefilli", "B1", "/ˈkɒm.plɪ.keɪ.tɪd/", "sıfat", "The algorithm seems complicated at first.", "Complicated puzzle."),
    ("Concentrate", "Odaklanmak, yoğunlaşmak", "B1", "/ˈkɒn.sən.treɪt/", "fiil", "Concentrate on one single task.", "Concentrate on studying."),
    ("Conclude", "Sonuçlandırmak, bitirmek", "B1", "/kənˈkluːd/", "fiil", "The author concludes with optimism.", "Conclude a meeting."),
    ("Confident", "Özgüvenli, kendinden emin", "B1", "/ˈkɒn.fɪ.dənt/", "sıfat", "Speak with a confident and clear voice.", "Self-confident."),
    ("Confirm", "Doğrulamak, onaylamak", "B1", "/kənˈfɜːm/", "fiil", "Please confirm your reservation.", "Confirm details."),
    ("Consequence", "Sonuç, netice", "B1", "/ˈkɒn.sɪ.kwəns/", "isim", "Every choice has a natural consequence.", "Direct consequences."),
    ("Consider", "Dikkate almak, düşünmek", "B1", "/kənˈsɪd.ər/", "fiil", "Consider all possibilities carefully.", "Consider options."),
    ("Contribute", "Katkıda bulunmak", "B1", "/kənˈtrɪb.juːt/", "fiil", "Every volunteer contributes to society.", "Contribute ideas."),
    ("Convince", "İkna etmek", "B1", "/kənˈvɪns/", "fiil", "His arguments convinced the whole committee.", "Hard to convince."),
    ("Crucial", "Çok önemli, hayati", "B1", "/ˈkruː.ʃəl/", "sıfat", "Consistent practice is crucial for fluency.", "A crucial decision."),
    ("Curiosity", "Merak, ilgi", "B1", "/ˌkjʊə.riˈɒs.ə.ti/", "isim", "Curiosity is the engine of intellect.", "Intellectual curiosity."),
    ("Defend", "Savunmak, korumak", "B1", "/dɪˈfend/", "fiil", "Defend human rights everywhere.", "Defend your thesis."),
    ("Deliberate", "Kasıtlı, planlı, sakin", "B1", "/dɪˈlɪb.ər.ət/", "sıfat", "Take deliberate steps toward your goals.", "A deliberate choice."),
    ("Demonstrate", "Göstermek, kanıtlamak", "B1", "/ˈdem.ən.streɪt/", "fiil", "Experiments demonstrate clear results.", "Demonstrate skills."),
    ("Determine", "Belirlemek, saptamak", "B1", "/dɪˈtɜː.mɪn/", "fiil", "Your habits determine your character.", "Determine priorities."),
    ("Disappoint", "Hayal kırıklığına uğratmak", "B1", "/ˌdɪs.əˈpɔɪnt/", "fiil", "Do not disappoint those who trust you.", "Do not be disappointed."),
    ("Distinguish", "Ayırt etmek, fark etmek", "B1", "/dɪˈstɪŋ.ɡwɪʃ/", "fiil", "Learn to distinguish fact from opinion.", "Distinguish between."),
    ("Diversity", "Çeşitlilik, farklılık", "B1", "/daɪˈvɜː.sə.ti/", "isim", "Cultural diversity enriches mankind.", "Biodiversity."),
    ("Efficient", "Verimli, etkili", "B1", "/ɪˈfɪʃ.ənt/", "sıfat", "An efficient routine saves precious hours.", "Energy efficient."),
    ("Emphasize", "Vurgulamak, öne çıkarmak", "B1", "/ˈem.fə.saɪz/", "fiil", "The professor emphasized core principles.", "Emphasize key words."),
    ("Encourage", "Cesaretlendirmek, teşvik etmek", "B1", "/ɪnˈkʌr.ɪdʒ/", "fiil", "Encourage your friends in hard times.", "Encourage learning."),
    ("Enormous", "Devasa, muazzam", "B1", "/ɪˈnɔː.məs/", "sıfat", "The universe holds enormous wonders.", "Enormous progress."),

    # ==================== B2 (ORTA ÜSTÜ - Akademik & Profesyonel Düzey) ====================
    ("Abstract", "Soyut, özet", "B2", "/ˈæb.strækt/", "sıfat", "Mathematics deals with abstract concepts.", "Abstract thinking."),
    ("Accomplish", "Başarıyla tamamlamak", "B2", "/əˈkʌm.plɪʃ/", "fiil", "You accomplished a magnificent task.", "Accomplish missions."),
    ("Acquire", "Edinmek, kazanmak", "B2", "/əˈkwaɪər/", "fiil", "Acquire valuable skills through study.", "Acquire knowledge."),
    ("Advocate", "Savunucu, savunmak", "B2", "/ˈæd.və.keɪt/", "isim", "She is a passionate advocate of clean energy.", "Advocate justice."),
    ("Ambiguity", "Belirsizlik, muğlaklık", "B2", "/ˌæm.bɪˈɡjuː.ə.ti/", "isim", "Clear contracts remove all ambiguity.", "Tolerate ambiguity."),
    ("Anticipate", "Öngörmek, tahmin etmek", "B2", "/ænˈtɪs.ɪ.peɪt/", "fiil", "Anticipate customer needs proactively.", "Anticipate problems."),
    ("Apparent", "Aşikar, belirgin, görünen", "B2", "/əˈpær.ənt/", "sıfat", "It was apparent that the theory was sound.", "Apparent reason."),
    ("Articulate", "Düşüncelerini net aktaran", "B2", "/ɑːˈtɪk.jə.lət/", "sıfat", "An articulate speaker captivates crowds.", "Articulate speaker."),
    ("Assert", "İleri sürmek, iddia etmek", "B2", "/əˈsɜːt/", "fiil", "Assert your ideas with politeness.", "Assert independence."),
    ("Authentic", "Özgün, otantik, gerçek", "B2", "/ɔːˈθen.tɪk/", "sıfat", "Live an authentic and honest life.", "Authentic documents."),
    ("Autonomous", "Özerk, bağımsız", "B2", "/ɔːˈtɒn.ə.məs/", "sıfat", "Autonomous vehicles will transform transit.", "Autonomous agent."),
    ("Capacity", "Kapasite, kabiliyet", "B2", "/kəˈpæs.ə.ti/", "isim", "Expand your mental capacity with reading.", "Full capacity."),
    ("Coherent", "Tutarlı, ahenkli", "B2", "/kəʊˈhɪə.rənt/", "sıfat", "Present a coherent and logical argument.", "Coherent essay."),
    ("Comprehensive", "Kapsamlı, geniş", "B2", "/ˌkɒm.prɪˈhen.sɪv/", "sıfat", "A comprehensive guide to English idioms.", "Comprehensive exam."),
    ("Contemplate", "Kafasında tartmak, derin düşünmek", "B2", "/ˈkɒn.təm.pleɪt/", "fiil", "Contemplate your future ambitions.", "Contemplate nature."),
    ("Contradict", "Çelişmek, aksini iddia etmek", "B2", "/ˌkɒn.trəˈdɪkt/", "fiil", "Actions should not contradict words.", "Contradict findings."),
    ("Conventional", "Geleneksel, alışılagelmiş", "B2", "/kənˈven.ʃən.əl/", "sıfat", "Challenge conventional ways of thinking.", "Conventional wisdom."),
    ("Criterion", "Kriter, ölçüt", "B2", "/kraɪˈtɪə.ri.ən/", "isim", "Efficiency is a vital criterion of quality.", "Selection criteria."),
    ("Decline", "Azalmak, düşüş, reddetmek", "B2", "/dɪˈklaɪn/", "fiil", "Inflation rates are expected to decline.", "Decline an offer."),
    ("Depict", "Tasvir etmek, betimlemek", "B2", "/dɪˈpɪkt/", "fiil", "Paintings depict rural historical life.", "Depict emotions."),
    ("Diminish", "Eksilmek, azalmak", "B2", "/dɪˈmɪn.ɪʃ/", "fiil", "True knowledge never diminishes with sharing.", "Diminish worries."),
    ("Discretion", "Sağduyu, takdir yetkisi", "B2", "/dɪˈskreʃ.ən/", "isim", "Handle confidential data with discretion.", "At your discretion."),
    ("Domain", "Alan, etki alanı", "B2", "/dəˈmeɪn/", "isim", "Mastery in the domain of artificial intelligence.", "Public domain."),
    ("Dynamic", "Dinamik, değişken", "B2", "/daɪˈnæm.ɪk/", "sıfat", "The modern global market is highly dynamic.", "Dynamic system."),
    ("Elaborate", "Ayrıntılı, detaylandırmak", "B2", "/iˈlæb.ər.ət/", "sıfat", "She gave an elaborate architectural plan.", "Elaborate further."),
    ("Emerge", "Ortaya çıkmak, belirmek", "B2", "/iˈmɜːdʒ/", "fiil", "Breakthrough innovations emerge from curiosity.", "Emerge victorious."),
    ("Equilibrium", "Denge, istikrar", "B2", "/ˌek.wɪˈlɪb.ri.əm/", "isim", "Maintain an equilibrium between work and rest.", "Mental equilibrium."),
    ("Evaluate", "Değerlendirmek, paha biçmek", "B2", "/ɪˈvæl.ju.eɪt/", "fiil", "Evaluate options before signing contracts.", "Evaluate progress."),
    ("Evolution", "Evrim, aşamalı gelişim", "B2", "/ˌiː.vəˈluː.ʃən/", "isim", "Study the evolution of communication tech.", "Cultural evolution."),
    ("Facilitate", "Kolaylaştırmak, zemin hazırlamak", "B2", "/fəˈsɪl.ɪ.teɪt/", "fiil", "Great teachers facilitate easy understanding.", "Facilitate dialogue."),
    ("Fluctuate", "Dalgalanmak, inip çıkmak", "B2", "/ˈflʌk.tʃu.eɪt/", "fiil", "Stock prices fluctuate throughout the week.", "Fluctuate wildly."),
    ("Formulate", "Formüle etmek, plan kurmak", "B2", "/ˈfɔː.mjə.leɪt/", "fiil", "Formulate a concrete strategy for victory.", "Formulate hypotheses."),
    ("Foster", "Geliştirmek, teşvik etmek, beslemek", "B2", "/ˈfɒs.tər/", "fiil", "Mentors foster creativity in young minds.", "Foster collaboration."),
    ("Hierarchy", "Hiyerarşi, aşama sırası", "B2", "/ˈhaɪə.rɑː.ki/", "isim", "Respect organizational hierarchy and teamwork.", "Social hierarchy."),
    ("Hypothesis", "Varsayım, hipotez", "B2", "/haɪˈpɒθ.ə.sɪs/", "isim", "Test the hypothesis through repeated trials.", "Scientific hypothesis."),
    ("Implement", "Uygulamak, yürürlüğe koymak", "B2", "/ˈɪm.plɪ.ment/", "fiil", "Implement modern code standards safely.", "Implement policies."),
    ("Imply", "İma etmek, anlama gelmek", "B2", "/ɪmˈplaɪ/", "fiil", "Silence does not imply agreement.", "Directly imply."),
    ("Incentive", "Teşvik, güdü", "B2", "/ɪnˈsen.tɪv/", "isim", "Bonuses act as an incentive for employees.", "Financial incentive."),
    ("Inherent", "Doğasında olan, ayrılmaz", "B2", "/ɪnˈher.ənt/", "sıfat", "Risk is an inherent aspect of investment.", "Inherent strength."),
    ("Insight", "İçgörü, kavrayış", "B2", "/ˈɪn.saɪt/", "isim", "Reading philosophy offers profound insight.", "Valuable insights."),

    # ==================== C1 (İLERİ DÜZEY - Zengin Dil, Nüanslar & Ustalık) ====================
    ("Abstain", "Çekinmek, oy kullanmamak, sakınmak", "C1", "/æbˈsteɪn/", "fiil", "Abstain from gossip and malicious speech.", "Abstain from voting."),
    ("Adversity", "Sıkıntı, talihsizlik, felaket", "C1", "/ədˈvɜː.sə.ti/", "isim", "True resilience is forged through adversity.", "Face adversity."),
    ("Aesthetic", "Estetik, güzellik algısı", "C1", "/esˈθet.ɪk/", "sıfat", "The building has remarkable aesthetic charm.", "Aesthetic appeal."),
    ("Allocate", "Pay etmek, tahsis etmek", "C1", "/ˈæl.ə.keɪt/", "fiil", "Allocate sufficient budget for research.", "Allocate time."),
    ("Ambivalent", "Çelişik duygular besleyen", "C1", "/æmˈbɪv.ə.lənt/", "sıfat", "He felt ambivalent about moving overseas.", "Ambivalent stance."),
    ("Anomaly", "Anomali, aykırılık", "C1", "/əˈnɒm.ə.li/", "isim", "Engineers detected an anomaly in the radar data.", "Statistical anomaly."),
    ("Benevolent", "Hayırsever, iyilik dolu", "C1", "/bəˈnev.əl.ənt/", "sıfat", "A benevolent philanthropist funded the school.", "Benevolent leader."),
    ("Coerce", "Zorlamak, baskı yapmak", "C1", "/kəʊˈɜːs/", "fiil", "No citizen should be coerced into silence.", "Coerce cooperation."),
    ("Cognitive", "Bilişsel, zihinsel", "C1", "/ˈkɒɡ.nə.tɪv/", "sıfat", "Bilingualism enhances cognitive flexibility.", "Cognitive faculties."),
    ("Coincide", "Denk gelmek, örtüşmek", "C1", "/ˌkəʊ.ɪnˈsaɪd/", "fiil", "Our travel schedules coincide perfectly.", "Coincide in time."),
    ("Compensate", "Telafi etmek, tazmin etmek", "C1", "/ˈkɒm.pən.seɪt/", "fiil", "Hard study compensates for lack of talent.", "Compensate damages."),
    ("Complacent", "Halinden memnun, rehavete kapılmış", "C1", "/kəmˈpleɪ.sənt/", "sıfat", "Winners never grow complacent after success.", "Complacent attitude."),
    ("Concur", "Aynı görüşte olmak", "C1", "/kənˈkɜːr/", "fiil", "Medical experts concur with the diagnosis.", "I concur with you."),
    ("Condone", "Göz yummak, hoş görmek", "C1", "/kənˈdəʊn/", "fiil", "The institution will not condone misconduct.", "Condone injustice."),
    ("Conspicuous", "Göze batan, dikkat çekici", "C1", "/kənˈspɪk.ju.əs/", "sıfat", "His bravery was conspicuous in the crisis.", "Conspicuous error."),
    ("Curtail", "Kısmak, sınırlandırmak", "C1", "/kəˈteɪl/", "fiil", "Curtail excessive screen time at night.", "Curtail expenses."),
    ("Deficit", "Açık, eksiklik, noksan", "C1", "/ˈdef.ɪ.sɪt/", "isim", "Address the attention deficit with patience.", "Budget deficit."),
    ("Deterrent", "Caydırıcı, engel", "C1", "/dɪˈter.ənt/", "isim", "Strong penalties act as an effective deterrent.", "Nuclear deterrent."),
    ("Discrepancy", "Tutarsızlık, uyumsuzluk", "C1", "/dɪˈskrep.ən.si/", "isim", "Accountants spotted a minor discrepancy.", "Wide discrepancy."),
    ("Emulate", "Örnek almak, benzemeye çalışmak", "C1", "/ˈem.jə.leɪt/", "fiil", "Aspire to emulate righteous role models.", "Emulate greatness."),
    ("Equivocal", "Çift anlamlı, şüpheli", "C1", "/ɪˈkwɪv.ə.kəl/", "sıfat", "His equivocal response created hesitation.", "Equivocal remarks."),
    ("Exemplify", "Örnek oluşturmak, somutlaştırmak", "C1", "/ɪɡˈzem.plɪ.faɪ/", "fiil", "Her courage exemplifies true leadership.", "Exemplify virtue."),
    ("Formidable", "Heybetli, dişli, ürkütücü", "C1", "/fɔːˈmɪd.ə.bəl/", "sıfat", "The chess grandmaster was a formidable foe.", "Formidable challenge."),
    ("Immutable", "Değişmez, sabit", "C1", "/ɪˈmjuː.tə.bəl/", "sıfat", "Mathematical laws are immutable and eternal.", "Immutable truth."),
    ("Imperative", "Zorunlu, elzem", "C1", "/ɪmˈper.ə.tɪv/", "sıfat", "Prompt climate action is globally imperative.", "Categorical imperative."),

    # ==================== C2 (USTA DÜZEY - Edebi, Felsefi & Üst Düzey Nüanslar) ====================
    ("Acumen", "Keskin zeka, feraset", "C2", "/ˈæk.jə.mən/", "isim", "Business acumen turned the startup into a giant.", "Financial acumen."),
    ("Alacrity", "Şevk, can atma, çeviklik", "C2", "/əˈlæk.rə.ti/", "isim", "He accepted the prestigious task with alacrity.", "With genuine alacrity."),
    ("Anachronism", "Çağ aşımı, zaman yanılgısı", "C2", "/əˈnæk.rə.nɪ.zəm/", "isim", "A smartphone in a medieval film is an anachronism.", "Historical anachronism."),
    ("Assiduous", "Sebatkar, canla başla çalışan", "C2", "/əˈsɪdʒ.u.əs/", "sıfat", "Assiduous research yielded historic cures.", "Assiduous scholar."),
    ("Banal", "Sıradan, beylik, basmakalıp", "C2", "/bəˈnɑːl/", "sıfat", "The dialogue in the movie was surprisingly banal.", "Banal speech."),
    ("Capricious", "Maymun iştahlı, sağı solu belli olmayan", "C2", "/kəˈprɪʃ.əs/", "sıfat", "Do not rely on the whims of capricious tyrants.", "Capricious climate."),
    ("Circumlocution", "Lafı dolandırma, dolambaçlı söz", "C2", "/ˌsɜː.kəm.ləˈkjuː.ʃən/", "isim", "Plain speech is always superior to circumlocution.", "Avoid circumlocution."),
    ("Conundrum", "Çözülmesi güç bilmece, muamma", "C2", "/kəˈnʌn.drəm/", "isim", "Ethical AI presents an intricate philosophical conundrum.", "Moral conundrum."),
    ("Deleterious", "Zararlı, tahripkar", "C2", "/ˌdel.ɪˈtɪə.ri.əs/", "sıfat", "Chronic stress has a deleterious effect on vitality.", "Deleterious habits."),
    ("Egregious", "Vahim, affedilmez, göze batan", "C2", "/ɪˈɡriː.dʒəs/", "sıfat", "Such egregious misconduct will not be excused.", "Egregious mistake."),
    ("Enigmatic", "Gizemli, esrarengiz", "C2", "/ˌen.ɪɡˈmæt.ɪk/", "sıfat", "The Mona Lisa wears an enigmatic subtle smile.", "Enigmatic thinker."),
    ("Evanescent", "Çabuk silinen, uçucu, geçici", "C2", "/ˌev.əˈnes.ənt/", "sıfat", "Rainbows cast an evanescent glow on the sky.", "Evanescent moment."),
    ("Fastidious", "Titiz, güç beğenen, müşkülpesent", "C2", "/fæsˈtɪd.i.əs/", "sıfat", "The fastidious editor vetted every punctuation mark.", "Fastidious taste."),
    ("Ineffable", "Kelimelerle anlatılamaz, tarifsiz", "C2", "/ɪnˈef.ə.bəl/", "sıfat", "A sunset of ineffable beauty stunned spectators.", "Ineffable peace."),
    ("Magnanimous", "Alicenap, yüce gönüllü", "C2", "/mæɡˈnæn.ɪ.məs/", "sıfat", "The victor showed magnanimous grace toward the defeated.", "Magnanimous gesture."),
    ("Nefarious", "Kötü niyetli, haince", "C2", "/nəˈfeə.ri.əs/", "sıfat", "The hero foiled the villain's nefarious scheme.", "Nefarious plots."),
    ("Obfuscate", "Kafasını karıştırmak, anlaşılmaz kılmak", "C2", "/ˈɒb.fʌs.keɪt/", "fiil", "Writers should illuminate ideas, never obfuscate them.", "Obfuscate facts."),
    ("Panacea", "Her derde deva ilaç", "C2", "/ˌpæn.əˈsiː.ə/", "isim", "Hard work is not a panacea for poor strategy.", "A universal panacea."),
    ("Pernicious", "Sinsi ve ölümcül, zararlı", "C2", "/pəˈnɪʃ.əs/", "sıfat", "Misinformation has a pernicious grip on society.", "Pernicious influence."),
    ("Sagacious", "Basiretli, bilge, ferasetli", "C2", "/səˈɡeɪ.ʃəs/", "sıfat", "A sagacious mentor steers youth with calm.", "Sagacious counsel."),
    ("Supercilious", "Kibirli, burnu havada", "C2", "/ˌsuː.pəˈsɪl.i.əs/", "sıfat", "Avoid supercilious disdain toward newcomers.", "Supercilious glare."),
    ("Taciturn", "Az ve öz konuşan, sessiz", "C2", "/ˈtæs.ɪ.tɜːn/", "sıfat", "The taciturn philosopher wrote monumental books.", "A taciturn character."),
    ("Venerable", "Hürmete layık, muhterem", "C2", "/ˈven.ər.ə.bəl/", "sıfat", "The venerable library stood for eight centuries.", "Venerable professor."),
    ("Voracious", "Doymak bilmez, obur, açgözlü", "C2", "/vəˈreɪ.ʃəs/", "sıfat", "She is a voracious reader of world classics.", "Voracious curiosity."),
    ("Zealot", "Bağnaz, fanatik", "C2", "/ˈzel.ət/", "isim", "Zealots rarely appreciate scientific skepticism.", "Religious zealot."),
]

def populate():
    print(f"Toplam eklenecek zengin kelime sayisi: {len(POPULAR_WORDS)}")
    existing = set(r[0].lower() for r in cursor.execute("SELECT word FROM dictionary").fetchall())
    print(f"Veritabaninda zaten var olan kelime sayisi: {len(existing)}")

    inserted = 0
    for w, t, lvl, phon, pos, defn, ex in POPULAR_WORDS:
        word_clean = w.strip().capitalize()
        if word_clean.lower() not in existing:
            meanings_json = json.dumps([{
                "part_of_speech": pos,
                "definition": defn,
                "example": ex
            }], ensure_ascii=False)

            cursor.execute(
                "INSERT INTO dictionary (word, translation, level, phonetic, meanings) VALUES (?, ?, ?, ?, ?)",
                (word_clean, t, lvl, phon, meanings_json)
            )
            existing.add(word_clean.lower())
            inserted += 1

    conn.commit()
    total_now = cursor.execute("SELECT COUNT(*) FROM dictionary").fetchone()[0]
    print(f"Eklenen yeni kelime sayisi: {inserted}")
    print(f"Veritabanindaki guncel toplam kelime sayisi: {total_now}")

    # Seviye dagilimini yazdir
    levels = cursor.execute("SELECT level, COUNT(*) FROM dictionary GROUP BY level ORDER BY level").fetchall()
    print("Guncel Seviye Dagilimi:")
    for lvl, count in levels:
        print(f"  {lvl}: {count} kelime")

    conn.close()

if __name__ == "__main__":
    populate()
